### ISSUE TITLE
Import Valves from 3D shape file raise an error

### ISSUE THREAD

**Issue by tproduit** [neslerel/QGISRed#19]
I 'm trying to import valves with 3D geometries but I get the following issue:
```
 CRITICAL    Error : at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource) 
              at ?????????????????????????????????????????.?????????????????????????????????????????(IEnumerable`1 , String ) 
              at ?????????????????????????????????????????.?????????????????????????????????????????(List`1 , Boolean , Boolean , List`1 ) 
              at GISRed.ExtendedModel.ExtendedScenario.ReadShpsFolder(Logger logger, String titleFile, List`1 shapeFiles, List`1 dbfFiles, List`1 fields, Boolean checkIds, Boolean checkCoord) 
              at GISRed.QGisPlugins.QGisPlugins.ImportFromShps(String dirPath, String networkName, String tempPath, String shapes, String fields)
```
The import of the exact same data with 2D geometry works.

**Comment by neslerel** [comment]
Could you send me an example of this 3D layer to test it?

**Comment by tproduit** [comment]
[3D.zip](https://github.com/neslerel/QGISRed/files/4613351/3D.zip)

**Comment by neslerel** [comment]
Hi @tproduit, 
In this file is only attached the .prj.
I need all the layer's files to test it... and know where is the problem.

Thanks!

**Comment by tproduit** [comment]
Sorry, something went wrong with my zip. Here you are. [valves3D.zip](https://github.com/neslerel/QGISRed/files/4613814/valves3D.zip)

**Comment by neslerel** [comment]
Thanks a lot @tproduit! 
I found the error and fixed it. 
Just today, we are going to release a new version (0.10) of the plugin.

**Comment by tproduit** [comment]
Great! Thank you. I'm looking forward to test the release.

**Comment by neslerel** [comment]
The new version (0.10) has been released two days ago.
Can you test if the error is fixed?
If yes, we can close the issue,

Thanks!

**Comment by tproduit** [comment]
I still encounter an error when I try to import something or create a new project but I guess that it is not related to the valves 
`
2020-05-15T13:47:16     CRITICAL    Error : at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, ServerProperties& properties) 
              at System.DirectoryServices.AccountManagement.PrincipalContext.DoServerVerifyAndPropRetrieval() 
              at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name, String container, ContextOptions options, String userName, String password) 
              at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType) 
              at System.DirectoryServices.AccountManagement.UserPrincipal.get_Current() 
              at GISRed.Model.Misc.Metadata..ctor() 
              at GISRed.Model.Scenario..ctor() 
              at GISRed.ExtendedModel.ExtendedScenario..ctor() 
              at GISRed.QGisPlugins.QGisPlugins.?????????????????????????????????????????(Logger& , ExtendedScenario& , String , String , Boolean , List`1 , Double ) 
              at GISRed.QGisPlugins.QGisPlugins.ImportFromShps(String dirPath, String networkName, String tempPath, String shapes, String fields, String epsg, String tolerance)
2020-05-15T13:48:17     CRITICAL    Error : The server could not be contacted.
`

**Comment by tproduit** [comment]
I tested it on a colleague's QGIS and it worked, the error above might be related to my QGIS (3.4)

**Comment by neslerel** [comment]
From the error you're showing, I'm guessing that it's when we try to get the username of your computer to use it as the name of the creator of the QGISRed project.
I suppose you use Windows, which version? and... 32 or 64 bits?
I think it is not problem of QGis version...

**Comment by tproduit** [comment]
Windows 10, 64 bit

**Comment by neslerel** [comment]
Thnaks! Maybe you are working in a Server or under a Domain. I'm going to handle this error.
