### ISSUE TITLE
Problem installing plugin in QGIS on Linux

### ISSUE THREAD

**Issue by IDoytchinov** [neslerel/QGISRed#50]
Dear all there is a problem and I cannot install your plugin : *(( As soon as it is installed I get this error: 

**ImportError: cannot import name 'WinDLL' from 'ctypes' (/usr/lib/python3.8/ctypes/__init__.py)**

_Couldn't load plugin 'QGISRed' due to an error when calling its classFactory() method 

ImportError: cannot import name 'WinDLL' from 'ctypes' (/usr/lib/python3.8/ctypes/__init__.py) 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/vnav/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QGISRed/__init__.py", line 34, in classFactory
    from .qgisred_plugins import QGISRed
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/vnav/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QGISRed/qgisred_plugins.py", line 32, in 
    from .ui.qgisred_projectmanager_dialog import QGISRedProjectManagerDialog
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/vnav/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QGISRed/ui/qgisred_projectmanager_dialog.py", line 7, in 
    from .qgisred_createproject_dialog import QGISRedCreateProjectDialog
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/vnav/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QGISRed/ui/qgisred_createproject_dialog.py", line 9, in 
    from ..tools.qgisred_dependencies import QGISRedDependencies as GISRed
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/vnav/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QGISRed/tools/qgisred_dependencies.py", line 2, in 
    from ctypes import c_char_p, WinDLL
ImportError: cannot import name 'WinDLL' from 'ctypes' (/usr/lib/python3.8/ctypes/__init__.py)

Python version: 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0] 
QGIS version: 3.16.3-Hannover Hannover, 94ac9f21b8 

Python Path:
/usr/share/qgis/python
/home/vnav/.local/share/QGIS/QGIS3/profiles/default/python
/home/vnav/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/vnav/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/usr/lib/python3.8/dist-packages
/home/vnav/.local/share/QGIS/QGIS3/profiles/default/python_

Any idea how to solve this?? Thanks a lot!

Iordan Doytchinov, Ph.D.

Postdoctoral researcher and scientific collaborator 

Ecole Polytechnique Fédérale de Lausanne (EPFL)
EPFL – TOPO
Station 18 – Bâtiment GC C2 398

CH–1015 Lausanne

Office telephone: +41216939832
Personal mobile: +33699850592

iordan.doytchinov@epfl.ch
http://topo.epfl.ch/

**Comment by neslerel** [comment]
Sorry @IDoytchinov, for now the plugin only works in Windows.
