### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'type' 

### ISSUE THREAD

**Issue by moval-agroingenieria** [neslerel/QGISRed#87]
Hola, 
QGISRed da el siguiente problema cuando modifico reiteradamente los atributos de las "pipe" en un modelo al tratar de ajustar las velocidades para un correcto diseño.
Si puedo hacer cambios en los elementos, guardar dichos cambios y simular con las nuevas condiciones; no obstante, tras una serie de pruebas, me sale el siguiente error. Parece ser que al ejecutar la simulación no crea correctamente el archivo .shx de los resultados.
Indico aquí imagen:
![image](https://user-images.githubusercontent.com/62283703/186887454-46a14146-1cc1-4b93-84c0-51795d74b17a.png)
Transcribo aquí el mensaje de error:

AttributeError: 'NoneType' object has no attribute 'type' 
Traceback (most recent call last):
  File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGISRed\qgisred_plugins.py", line 2530, in runModel
    self.ResultDockwidget.simulate(self.ProjectDirectory, self.NetworkName)
  File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGISRed\ui\qgisred_results_dock.py", line 800, in simulate
    self.saveCurrentRender()
  File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGISRed\ui\qgisred_results_dock.py", line 268, in saveCurrentRender
    if renderer.type() == "graduatedSymbol":
AttributeError: 'NoneType' object has no attribute 'type'
Versión de Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versión de QGIS: 3.18.1-Zürich Zürich, 202f1bf7e5 

muchas gracias

**Comment by neslerel** [comment]
Hola @moval-agroingenieria,
Por lo que veo en la captura parece ser más un problema en el código a la hora de guardar los estilos de las capas de resultados para volverlos a aplicar a los nuevos resultados, más que que no genere los .shx.
Voy a ver si consigo reproducirlo con cualquier red y si es así, lo intentaremos solucionar.
¿Si borras manualmente las capas de resultados desde la leyenda y vuelves a simular, funciona?

Saludos y gracias por reportarlo.

**Comment by neslerel** [comment]
He estado haciendo unas cuantas pruebas y no he conseguido reproducirlo... No sé si se debe a la red en concreto, algún cambio que genera alguna velocidad anómala o que no estoy haciendo lo que toca para reproducirlo.
¿Podrías grabar un vídeo para saber exáctamente los pasos?
¿Cambias el estilo de la capa de resultados en algún momento?

**Comment by neslerel** [comment]
Gracias @moval-agroingenieria por el feedback. 
Aunque borrar las capas sea una solución, no es lo ideal. Trataremos de reproducirlo y de solucionarlo.

Saludos

**Comment by neslerel** [comment]
Hemos hecho muchos cambios en la parte de resultados y sus capas.
Hemos sacado una nueva [versión beta](https://github.com/qgisred/QGISRed/issues/166). Puedes probarla y comentar cualquier issue que tengas. Gracias!
